sky-uk/mite

- README.md
- docs/conf.py
- docs/index.rst
A few little fixes to the docs
> Docs fixes

- cd.yml
- Use our own slave type
- Remove unneeded job
> Cleanup the cd.yml file

- mite/__main__.py
- mite/controller.py
- mite/datapools.py
- mite/scenario.py
- mite/zmq.py
- test/test_datapools.py
- test/test_scenario.py
All the checkin and checkout method inside  the datapool file has been changed to use async.
As consequence there are multiple changes in other components and them unit tests in order to reflect the datapool update.
> Making datapools checkin/checkout async

- mite_http/__init__.py
- test/test_mite_http.py
For our chaos testing, weʼre interested in requests that take
longer (2-6 seconds).  The logarithmic buckets provide poor coverage for
this use case.  So weʼd like to override the buckets with something
different.  This lays the groundwork in mite that we need for that.
We use an environment variable for this, because the modular structure
of mite means that thereʼs not an easy way to pass a command line
argument in here.
> Allow specifying custom buckets for mite http stats

- mite/__main__.py
See the comment in the code for explanation
> Attempt to fix a race with the runner exit

- mite/__main__.py
- mite/cli/test.py
- mite/logoutput.py
Add functionality to stop scenario test when work finished and return status code based on nr of total errors
> Exit scenario test when work finished

- mite_browser/__init__.py
- test/test_mite_browser.py
* Fixed at least one bug with parsing of elements with a disabled attribute
* Added 30% coverage of unit tests to the mite_browser
* Increased overall unit test coverage by ~4%
> Fixed bugs in browser, added unit tests

- cd-scripts/runTests.sh
- dev-requirements.txt
- mite/__init__.py
Unit tests passed so hopefully no side effect
> Stipped out passing loop to the sleep

- README.md
**What is the change**
- Corrects a typo in the readme
**Why has the change been made**
- ~~So I can be listed as a contributor~~
> Removed typo in Readme.md

- mite_http/__init__.py
- test/test_mite_http.py
Fix the http session pool memoization
Since the memoization was introduced, it had a defect which was that the
event loop was fetched at decorator execution (= function definition) time,
not at function call time.  We would not notice this in our core tests,
which all run under a single mite event loop, but it led to problems in the
id-mite-nft test suite that were importing and evaluating journey
functions in different event loops, importing outside loops, etc.
This fixes the memoization to occur at the correct time, and adds some
unit tests for the problem.  It also ports the contextmanager to use the
new (in 3.7) asynccontextmanager decorator for slightly less verbosity
> Fix the http session pool memoization

- mite_browser/__init__.py
- test/test_mite_browser.py
Fix mite_browser for mite_http api change in #134
Also add unit test
> Fix mite_browser for mite_http api change in #134

- setup.cfg
The module was renamed and weʼre not pulling in updates any more
https://github.com/msgpack/msgpack-python#pypi-package-name
> Pull in new versions of the msgpack module

- .pre-commit-config.yaml
- docs/components.rst
- docs/design-deployment.rst
Add receiver to docs/components
Add receiver to docs/design-deployment
> Add receiver component to docs

- test/test_scenario.py
Renaming `baseline_rumpup_mock` to `baseline_rampup_mock` 🐮
> Renamed the test scenario rampup mock

- mite_browser/__init__.py
Most of the changes are just quote marks; the actual changes are
removing `async` from the
get_cookie_list/erase_all_cookies/erase_session_cookies methods
> Update mite_browser for the changes in #165

- mite/volume_model.py
Jira ticket: https://agile.at.sky/browse/IPB-7595
> IPB-7595 Add duration and tps to oneshot_vm

- mite/__main__.py
also includes linter-driven quote changes
> Fix docstring

- mite_selenium/__init__.py
- mite_selenium/stats.py
> JS context timing 

- mite/__main__.py
- mite/cli/test.py
Add a `--memory-tracing` argument to `mite journey|scenario test`
> memory debugging support

- mite_selenium/__init__.py
- Adding a new method for waiting for multiple elements on a page to appear.
> Adds wait_for_elements method to mite selenium

- .pre-commit-config.yaml
- DEV.md
- cd-scripts/runTests.sh
- tox.ini
We will need to wait until alpine linux is on 3.9 to merge this (because of our CI...)
> updates for 3.9

- cd-scripts/runTests.sh
remove a layer of virtualenv wrapping and make things faster (fewer iterations inf installing dependencies)
> speedup the ci

- mite/har_to_mite.py
- test/test_har_to_mite.py
Changes added to extract timings from har file.
NB the sleep time for the first entry will always be zero as there is no preceding time. I have assumed that non-zero user supplied sleep times take precedence over captured times.
> IPB-7683 - extract timings from har file§

- mite/scenario.py
Add the check on the scenario list size at line 136 and log out if the all scenarios have been removed from the scenario tracker. 
_Extra: quotes substitution by black and import sorted by isort_
> Add info log if all scenarios have been removed

- mite/scenario.py
Fix a typo that passed latest review.
> Fix small typo

- mite_selenium/__init__.py
Add two functions in order to move back after switching into an iframe in mite_selenium
> Add switch_to default_content and parent_frame in mite_selenium

- mite_http/__init__.py
Create a function to create a http cookie base on the acurl used
> Create http cookie based on acurl

- local/demo.py
- mite/scenario.py
- mite/volume_model.py
- test/perf/mite_perftest.py
- test/test_controller.py
- test/test_volume_model.py
Card : https://agile.at.sky/browse/IPB-18375
This is just a name change of an exception from StopScenario to StopVolumeModel
> Renaming StopScenario to improve ambiguity 

- README.md
changing StopScenario to StopVolumeModel in the Readme file which I forgot to do with https://github.com/sky-uk/mite/pull/249 🤦‍♂️
> Fixing the readme file

- cd-scripts/cdTagRelease.sh
After some other manual test upgrade the push from testpypi to mite pypi
> Update package push from test-pypi to pypi

- acurl/setup.cfg
- acurl/tests/test_acurl.py
- mite/__init__.py
- mite/stats.py
- mite_kafka/__init__.py
- test/test_mite_kafka.py
- test/test_stats.py
Fixes all but one warning in the mite ci
> Warning fix

- mite/volume_model.py
Enabling StopVolumeModel by tweaking the if condition.
> Enabling StopVolumeModel

- docs/journeys.rst
Fixed minimum examples in `journey.rst` that were not consistent or wrong and therefore didn't run without edits.
> Fix data creation example in the docs

- dev-requirements.txt
- test-requirements.txt
Bump up package versions to increase versions of some transient dependancies as well.
> review and update dependancies

- docker_compose.yml
- test-requirements.txt
[Snyk]
Version upgrades to fix 1 vulnerabilities in the project.
> Security Upgrades: setuptools to >= 78.1.1 - Docker-compose image to python:3.11-alpine3.19

- Dockerfile
- acurl/tests/test_acurl.py
- acurl/tests/test_httpbin.py
- acurl/tests/test_request.py
- acurl/tests/test_response.py
- acurl/tests/test_session.py
Upgrade `python:3.11-alpine3.16` to `python:3.11.13-alpine3.22` to fix some vulnerabilities
> Upgrade dockerfile base image

- acurl/pyproject.toml
- acurl/setup.cfg
- acurl/setup.py
- acurl/src/acurl.pyx
- acurl/src/session.pyx
- test-requirements.txt
https://devex-issuehub.at.sky/browse/IDSREPERF-13 - Update cython and uvloop compatibility for acurl
> IDSREPERF-13 - Cython 3x migration
