mite/config.py

If the logs are captured somewhere, this leaks secrets.  If you want to
debug the setup of the config, then you can add debugging code to the
scenario function to do so (e.g. to dump the config to stdout, if thatʼs
what you want to do).

Donʼt log the value of config variables that we set

---

mite/__main__.py
mite/cli/duplicator.py
mite/zmq.py
test/perf/perftest.py
test/perf/run-perftest.sh

This allows us to do `kill -USR1 <pid>` and force the duplicator to dump
100 messages to stdout.  This is useful for debugging live systems,
especially in the cloud where inserting debugger breakpoints isnʼt
feasible.
Probably needs to be performance benchmarked.

Add the ability to dump some messages for debugging to the duplicator

---

README.md

* the readme docker run command uses the bash shell as entry-point which is not available so switched to sh

Fix readme docker run command

---

mite/__main__.py
mite/cli/common.py
mite/cli/test.py

This allows us to do some fancy things.  Iʼve used this in chaos testing
to print out the request id of any request that takes longer than 5s.
(This change is technically not needed for the journey test command
itself, since we can print() from whereever we want in the code.  But it
allows us to test the message bus adapters that we write in the test
commands, eventually to plumb them into the message bus in a real
test – that is, this change facilitates debugging a custom component
like a stats, collector, etc. as part of journey test.)

Make the message bus configurable for the journey/scenario test commands

---

mite/cli/test.py

This is related to some of the recent async changes.  Iʼm not sure
how/why it hasnʼt turned up til now, but here it is.... *shrug*

Fix a problem with mite scenario test

---

acurl/tests/test_httpbin.py
mite/__main__.py
mite/stats.py
mite/zmq.py
test/test_controller.py
test/test_recorder.py
test/test_runner_tracker.py
test/test_stats.py
tox.ini

Substantive changes:
- Change the semantics of the `Gauge` stat to report the last-seen value, not a sum.  We have the "Counter" and "Accumulator" stats for reporting sums.
- Consequent change to the tests
- Fix a bug whereby the controller was not sending its reports, and therefore the `mite_runner_count` metric (and a couple others) would not appear in prometheus
- Add a test for this
- Allow the scenario function to receive a sender object for the mite data pipeline if needed.  Dependency-inject this, and the config argument, "properly" (by looking at the signature of the function).
Test changes:
- introduce a "slow" mark for tests.  You can skip the slow tests locally by running `pytest -m "not slow"`
- fix a deprecation warning in the test suite from msgpack library
At …

Several changes

---

mite/__main__.py
mite/datapools.py
mite/scenario.py
test/test_datapools.py

Because of a necessity I tried to add the opts from the config to the datapool.
As consequence I added to the datapools  a **kwargs argument in the checkout method that can be used for getting the necessary opts.

Passing the opts from the config to the datapools

---

mite_browser/__init__.py

This has been broken for a long time, but itʼs only now started to
actually cause exceptions...Iʼm not 100% sure why, but letʼs just fix
it.

Fix the url regex in mite browser

---

mite_websocket/__init__.py
test/test_mite_websockets.py

After founding out that in the current state I wasn't able to receive the message from the server I did some changes.
- When a connection is created it will be added on a list and returned. 
- To send and receive messages is enough to use the returned obj from the connection method.
- There is a new method to get the list of created connection
- A new close method as been added. It will close the connection, remove it from the list and delete it. 
- At the end the whole list will be scanned and all the connection closed.

Mite websocket update

---

mite_http/__init__.py
mite_http/stats.py
mite_selenium/__init__.py
mite_selenium/stats.py
setup.cfg
test/test_mite_http.py

Weʼve seen memory usage slowly balloon in the stats component when new
modules pull in new dependencies.  The best pattern for keeping mem
usage low seems to be to keep the stats definitions in separate modules,
which this PR implements for mite core.

Split stats into their own modules

---

mite/utils.py

strict_map_key prevents using integers as map keys when we unpack
messages (only str and bytes are allowed).  But the runner wire format
uses ints as keys.  The point of the setting of this option to true by
default is to be secure against hashtable-based DoS attacks.  But since
this is a mite-internal protocol, I think we are safe to set it to false.

Fix bug introduced with msgpack upgrade

---

mite/__main__.py
mite/cli/cat.py

- Move the cat command to its own file in the mite.cli package
- Fix a bug introduced by the recent msgpack upgrade (`encoding` arg was removed)
- Make the output format of `mite cat` be JSON
- Add an `uncat` command which performs the inverse of the cat operation

Enhancements and fixes for "mite cat"

---

mite/context.py
test/test_context.py

Implement stack-walking logic for error reporting in mite.  This (finally) stops all the errors in the mite dashboard from being reported at the same location `/home/aecay/work/id-mite-nft/mite/mite/context.py:59:transaction`

Accurate tracebacks

---

.pre-commit-config.yaml
acurl/src/response.c
tox.ini

I believe this was introduced by https://github.com/curl/curl/pull/4434

Fix a bug where on recent versions of curl cookies wouldnʼt work properly

---

mite_browser/__init__.py
mite_http/__init__.py

Adding a Session wrapper in mite_http in order to allow the session modification without break the original mite session.

Adding a session wrapper for additional metrics

---

mite/context.py
mite/stats.py
test/test_runner.py

- a better way of generating more accurate error location info
- a better way of converting exceptions to strings.
`str(KeyError("foo")) == "foo"`, which is less than optimal
- remove a mutable default kwarg

Fixes for mite traceback reporting

---

.isort.cfg
README.md
mite/__main__.py
mite/context.py
mite/runner.py
setup.cfg

Uncoupled mite's dependency upon the ipdb debugger and therefore also decoupled from a direct dependency upon IPython.
This pull pull request:
- Removes references to and dependencies upon ipdb.
- Replaces calls to `ipdb.post_mortem()` and `ipdb.set_trace()` with a call to Python 3.7's `breakpoint()` built-in.
- Documents the new behaviour of mite's `--debugging` flag.
If mite is executed using the `--debugging` flag, then Python's default debugger, pdb, is invoked unless `PYTHONBREAKPOINT` has been set to override this behaviour.
The ipdb debugger can still be used for debugging, but it must first be explicitly pip-installed (along with its dependencies, such as IPython).

Enhanced --debugging capability

---

acurl/tests/test_httpbin.py
acurl/tests/test_to_curl.py
pyproject.toml
test-requirements.txt

The web version of httpbin is flaky for a variety of reasons, but we can just use a local version

Fix the httpbin tests

---

.isort.cfg
acurl/acurl/__init__.py
acurl/src/response.c
acurl/src/session.c
acurl/tests/helpers.py
acurl/tests/test_httpbin.py
acurl/tests/test_request.py
acurl/tests/test_to_curl.py

Fix for request cookies not returning session cookies
- Remove the cookie_list property on Request objects.  Itʼs not part of
the requests API, and it raises thorny questions (should we really be
returning a list?)  The underlying data is available on the
`_cookie_tuple` property if someone really needs it.
- Make Requests store a copy of the session cookies when created.
Thereʼs a bit of an issue here in that it causes us to do extra
processing when every Request is created.  My first implementation
idea was to store a reference to the session in the Request class and
do the calculation in the cookie property – but since the session is
mutable, that means the cookies could have changed in the mean time.
So Iʼm not sure if I see an alternative to this....
- Make the session cookie …

 Fix for request cookies not returning session cookies

---

acurl/tests/test_response.py
cd-scripts/runTests.sh

this came up in our idris testing; we had to hack around this by
inspecting headers directly.  now itʼs resolved through recent code
changes, but this test case proves (and maintains) that fix, so we can
take away the hack in our private test suite code

add a test for a previously problematic multi-cookie case

---

README.md
mite/context.py

It turns out that there are differences between set_trace and
post_mortem debugger calls.  Unfortunately PEP553 doesnʼt support
customizing the latter, so we have to DIY.

Restore postmortem debugging

---

.gitignore
mite/logoutput.py
mite/web/prometheus.py
mite_selenium/__init__.py
mite_selenium/stats.py
test/mocks/mock_selenium.py
test/test_prometheus_mite.py
test/test_webdriver.py

-Added metrics for mite selenium tests, including both page load metrics and network resource metrics for downstream resources.
- Fixed a bug regarding the Histogram whereby the bin_counts was being used to iterate on and append the metrics. if all of the metric value fell in the infinite bin, this would mean there was nothing to iterate through and therefore would not append the metrics.
- Some mad formatting.

Selenium built in page load metrics and context manager

---

mite_selenium/__init__.py

These changes give access to the Selenium webdriver via context. Normally classes wrapped by _SeleniumWrapper proxy calls to webdriver methods through that class's methods - for instance to collect statistics. However, there are cases where proxied access isn't required or desirable.

Provide access to the Selenium webdriver instance on _SeleniumWrapper

---

mite/__main__.py
mite/cli/common.py
mite/cli/test.py

Make the `scenario test` add the sender automatically in the scenario arguments. It involved moving the check in the `cli/common.py` and import it in both `__main__.py` and `cli/test.py`
The changes from `'` to `"` are done automaticcaly by black.

Make scenario test pass the 'sender' automatically

---

mite_selenium/stats.py

remove stray `http` that was mistakenly left.

Rename selenium metric

---

acurl/tests/test_httpbin.py

- Added tests to cover scenario whereby cookies should be sent to domain on subsequent requests after being dropped on the initial request.

Test session cookies sent on subsequent requests

---

acurl/src/acurl.h

`acurl.h` was missing the `perform_request()` function prototype, causing a gcc build error in some (but not all) versions of gcc when running `pip install acurl`. This PR adds the prototype to `acurl.h` to fix that issue.

Fix to add missing perform_request() function prototype.

---

acurl/acurl/__init__.py
acurl/tests/test_cookie.py
acurl/tests/test_to_curl.py

Adding a cookie wrapper to allow for the overriding of the cookie domain, name and value when required.

Adding cookie wrapper to allow for overriding cookie domain

---

mite/datapools.py

In my testing, I couldnʼt reproduce the error reliably.  But if a stale
runner from a previous test run was hanging around, then it would
trigger the behavior we saw.  I canʼt figure out why we would have had
such a stale runner in our overnight test – it should have been a clean
environment – but in any case, this change converts an exception into an
error log, to prevent us from crashing in this case

Fix an error weʼve seen after #182

---

mite/scenario.py

Add a small check on the scenario list size at line 68 and log out if the all scenarios have been removed from the scenario tracker.

Log out if the all scenarios have been removed from the scenario tracker

---

mite_selenium/__init__.py
setup.cfg
test/test_webdriver.py

- fix name of `_spec_import_if_not_none`
- make the name of the setuptools extra lower_snake_case (which seems to be the most common casing in the wild...)
- change how the `wire` argument is passed through the call chain
- raise an early, descriptive error is selenium-wire is needed but not found
- fix a bug in the case where seleniumwire_options is not given
- make it possible to invoke `mite_selenium` with or without parens
- add unit test coverage for both cases

Review comments

---

.isort.cfg
mite_selenium/__init__.py
setup.cfg
test/test_webdriver.py

Use selenium remote driver quit instead of stop to avoid exhausting the selenium browser sessions/instances while waiting for browser timeouts

Add selenium-wire support

---

Dockerfile.perftest
acurl/.gitignore
acurl/src/cookie.pyx
acurl/src/request.pyx
acurl/src/response.pyx
acurl/src/session.pyx
acurl/src/utils.pyx
acurl/valgrind/README.md
acurl/valgrind/leak_check.py
acurl/valgrind/valgrind-python.supp
mite_http/__init__.py
test/perf/run-perftest.sh
test/test_mite_http.py

Here are the fixes and things we talked about a couple weeks ago.  I've split the commits up by purpose, and also ordered them into blocks for ease of reviewing/digesting.
- Commits up to 920d (inclusive) are docs/tooling/cosmetic
- f2be is a fix to the mite test suite removing a questionable mock that would cause the new acurl code to trip
- 73bf and 665c are documentation fixes inside the acurl code
- 30c0 and 7c18 are code changes unrelated to mem leak stuff
- and finally, 7d57 to the end are mem leak fixes

Acurl cleanups and memleak fixes

---

mite/cli/test.py
mite/collector.py

Occasionally when sending a message it would not write to the collector file. The buffered writer is only written to under the conditions [[0](https://docs.python.org/3/library/io.html#io.BufferedWriter)]: 
- when the buffer gets too small for all pending data;
- when flush() is called;
- when a seek() is requested (for BufferedRandom objects);
- when the BufferedWriter object is closed or destroyed.
The odd message would get missed, I believe due to the `Collector` object being destroyed before a `close` is called on our writer object. This PR ensures a `flush` is called after every write.

Flush the raw message after writing

---

mite/__main__.py
mite/cli/test.py

Sometimes when running a big amount of journeys a single error can be irrelevant and making fail the whole job can be annoying. This will allow mite to set an exit status of 0 even if we got some error if the number will be lower than the set threshold.

Add a new option to set an error threshold in the scenario command

---

acurl_ng/src/acurl.pyx
acurl_ng/src/curlinterface.pxd
acurl_ng/tests/test_acurl_ng.py
acurl_ng/tests/test_response_ng.py

Curl will return a non-zero exit code when something goes wrong.This change is to raise an AcurlError that describes the error code. See https://curl.se/libcurl/c/libcurl-errors.html and https://everything.curl.dev/usingcurl/returns for details.
Skipping http 100 tests for now since this change revealed a problem with them a.i. they hang because curl returns CURLE_RECV_ERROR (56) instead of CURLE_OK (0).

Raise AcurlError on non-zero exit code

---

acurl_ng/tests/test_response_ng.py

Fixes the broken tests from #224
Instead of creating a dummy http server, it's using pytest-httpserver and sending the `Expect: 100-continue` header.
We can confirm that we get a "100 Continue" followed by "200 OK" by looking at `r.header`:
```HTTP/1.1 100 Continue\r\n\r\nHTTP/1.0 200 OK\r\nFoo: bar\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 0\r\nServer: Werkzeug/2.0.1 Python/3.9.9\r\nDate: Wed, 24 Nov 2021 11:40:31 GMT\r\n\r\n```
Removed this test. `CURLINFO_RESPONSE_CODE` should always have the last received response code, so we can be pretty confident we're safe against this corner case.

Fix HTTP 100 test

---

setup.cfg

Using the latest version of Selenium causes incompatibility issues with Rust. Setting the version to less than 4 prevents this issue. 
Note that this will need to be revised when we upgrade to Selenium 4. The card for that work - https://agile.at.sky/browse/IPB-15616 - has been updated to capture this.

IPB-16472 Fix Jenkins Slave Image Rust issue

---

README.md
docker_compose.yml
docker_compose_monitoring.yml
grafana/provisioning/dashboards/mite_docker.json
local/README.md
local/demo.py
local/run_mite.sh
prometheus/prometheus_config_docker.yml
prometheus/prometheus_config_template.yml

Expanding on changes from https://github.com/sky-uk/mite/pull/230
- Updated `README.md`, removed `pip install mite` command and working instructions
- Use a mount for journeys in the docker image, so it doesn't need to be rebuilt on changes to tests
- Use an environment variable within docker-compose and the demo scenario for the `API_URL`
- Update the docker grafana dashboard config to working correctly
- In the prometheus config for docker, changed the prometheus target from `mite-prometheus_exporter-1` to `prometheus_exporter` (The containers were named as `mite_prometheus_exporter_1` on my machine, [looks like a version thing?](https://stackoverflow.com/a/69519102))
- In the prometheus config for local tests, changed the prometheus target from `127.0.0.1` to `host.docker.internal` and …

docker fixes etc

---

test-requirements.txt

It looks like pinning the version of werkzeug to 2.0.3 may fix this issue we are seeing with 2.1.0

pinned version of werkzeug

---

mite/cli/cat.py
mite_http/__init__.py

I'm not sure if it's related to using the new acurl, but.. the http method was getting sent with the type bytes, causing `mite cat` to fail, e.g.
```
$ mite cat collector_data/current
{"start_time": 1657611774, "effective_url": "http://localhost:9898/", "response_code": 200, "dns_time": 6e-06, "connect_time": 6e-06, "tls_time": 0.0, "transfer_start_time": 1.4e-05, "first_byte_time": 0.000248, "total_time": 0.000252, "primary_ip": "127.0.0.1", "method": Traceback (most recent call last):
File "/Users/rli14/mite/mite_env/bin/mite", line 33, in <module>
sys.exit(load_entry_point('mite', 'console_scripts', 'mite')())
File "/Users/rli14/mite/mite/__main__.py", line 352, in main
cat(opts)
File "/Users/rli14/mite/mite/cli/cat.py", line 24, in cat
json.dump(row, sys.stdout)
...
TypeError: Object …
```

Allow `mite cat` to cat bytes (#241) 🐱

---

.circleci/config.yml

When grep'ing for the acurl version, make sure we check the version number AND the end of the line.
For cases when the current version number is `1.0` but the updated version is `1.0.1` a match would occur, causing a failure, even when the version number has changed.

Correctly check acurl version

---

.circleci/config.yml
acurl/setup.cfg

Even though it worked testing it on my own repo, for some reason it's complaining it can't tag with the error:
```
*** git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
cmdline: git tag -m Automatic version tag v0.0.1 v0.0.1 HEAD
stderr: 'Committer identity unknown
*** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: unable to auto-detect email address (got 'circleci@3c648b6445d6.(none)')'
```
Adding the following lines _should_ fix it
```bash
git config user.email "mite@noreply.github.com"
git config user.name "CircleCI"
```
---
Also added a version change for acurl to test the build/push …

Add git identity for circleci git tag

---

.circleci/config.yml
.github/pull_request_template.md
cd-scripts/cdRelease.py

Introducing a basic PR template to include versioning options. Allowing you to choose which version segment you increment.
Modified the `cdRelease.py` script to get the version segment to increment from the PR.
With this PR, I've chosen to increment `Major' as the PyPi versions are muddied due to taking over the namespace from an old project (and a little from myself by not pushing test packages to test.pypi.org 😊).
The used versions are:
```
0.1.16 | August 10th, 2022 06:24
0.1.15 | August 8th, 2022 19:41
0.1.10 | August 4th, 2022 16:12
0.1.9 | August 4th, 2022 14:59
0.1.7 | August 4th, 2022 14:44
0.1.6 | August 4th, 2022 14:15
0.1 | March 21st, 2022 12:03
0.0.8 | November 22nd, 2018 11:28
0.0.7 | July 29th, 2018 18:09
0.0.6 | July 29th, 2018 18:09
0.0.5 | July 29th, 2018 17:47
0.0.4 | …
```

Better versioning

---

.circleci/config.yml
cd-scripts/cdRelease.py

From https://github.com/sky-uk/mite/pull/246 I made the assumption that `CIRCLE_PULL_REQUEST` would be available during the master build. Unfortunately that's not the case and instead we need to get the PR info from `git log --format=%B -n 1`
Hopefully third time is the charm and it works this time 😮‍💨

Correctly get PR body when ran from master

---

mite_selenium/__init__.py

The error log string in the _extract_entries function contains a hard corded expected value of 1. The function is called in line 96 (_timings) with an expected value of 1, but it is also used in line 123 (_paint_timings) with an expected value of 2. The expected values difference can help debugging but the string would always log 1, causing confusion on which call actually failed.
Not really.

fix mite selenium _extract_entries log string

---

.circleci/config.yml
dev-requirements.txt
mite_browser/__init__.py

As we now use "acurl_ng" by default, the Session object doesn't have a `request` method, so mite_browser was broken and you would get the following error:
```
AttributeError: AttributeError: 'acurl.Session' object has no attribute 'request'
```
This PR finds the methods function and calls that instead.

Fix mite_browser calls the http methods

---

setup.cfg

Change selenium-wire required version from >=4.3.0 to ==4.6.5.
We did not have a "successful" (was green but not journey runs) frontend test since the 26th of September 2022 because of `Controller job died prematurely or waiting timed out`. Running the test locally raises `ImportError: cannot import name 'EdgeOptions' from 'selenium.webdriver'`, which can also be observed on the pods log (runners only). Strangely enough, the pods status show "Completed" rather that "Error"...
On the same date we started to observe the issue, was release selenium-wire version 5.0.0. Testing with the previous release (4.6.5) seems to fix the tests.

Change selenium-wire required version from >=4.3.o to ==4.6.5

---

.circleci/config.yml

Using the `python:3.11.2` image, we now need to specify the full path for twine.

Fix twine path for uploading Linux wheels

---

acurl/MANIFEST.in
acurl/setup.cfg
mite/cli/test.py

A previous PR: https://github.com/sky-uk/mite/pull/254 Introduced a bug that will never allow a scenario test to finish running.
This PR fixed that by replacing the asyncio `gather` call with a `wait` call with the `return_when=asyncio.FIRST_COMPLETED` parameter.
This was tested by creating the following scenario and running the command:
```
$ mite scenario test a:scenario --log-level=WARN
Stopping Scenario
```
```python
import asyncio
from mite.scenario import StopVolumeModel
def volume_model_factory(n):
def vm(start, end):
if start > 1:
print("Stopping Scenario")
raise StopVolumeModel
return n
vm.__name__ = f"volume model {n}"
return vm
def scenario():
return [
["a:j", None, volume_model_factory(1)],
]
async def j(ctx):
await asyncio.sleep(1)
```
Also added `*.pyx` and `*.pxd` files to …

Fix `mite scenario` never completing when scenario is finished

---

mite_selenium/__init__.py

On instanciation of a new webdriver, the _options attribute is set to a reference of a webdriver options object (e.g. selenium.webdriver.chrome.options.Options). This causes any modification of the options to be reflected on possibly all the running webdrivers, or at the very least, on the webdrivers created after modification of the options.
As an example, when a webdriver is created by seleniumwire, its options are somehow modified by seleniumwire to comprise the proxy address. This causes all webdrivers, or at least the ones created after the options modification, to use that proxy as well.

Fix shared browser options between wire and non wire journeys

---

.circleci/config.yml

Remove the step to build a compiled acurl OSX wheel.
(Too much work to maintain it when the majority of people using this on a MacOS should have the correct build dependencies installed anyway)

Remove OSX Wheel step

---

.circleci/config.yml
cd.yml

Temporarily disable the ci jobs while looking for another platform to run them as the parent department moved away from circle-ci.

Disable ci jobs temporarily  

---

acurl/tests/test_acurl.py
docker_compose.yml
docker_compose_monitoring.yml

Version key is deprecated and now longer used

remove deprecated version key from docker compose

---

mite/__main__.py
mite/cli/test.py
mite/logoutput.py
mite_http/__init__.py

Adds the following options:
```
--report                                  Report stats at the end of the test
--hide-constant-logs                      Hide logs that are printed every 2 seconds
--max-response-time-threshold=THRESHOLD   Set the maximum response time accepted before setting exit status to 1 [default: 0]
--mean-response-time-threshold=THRESHOLD  Set the mean response time accepted before setting exit status to 1 [default: 0]
```
`--report` will print out a report , e.g.
```
Avg             Min             Max
Latency         40.75ms         1.90ms          1026.44ms
Req/Sec         9.97            9.48            10.50
110 requests in 11.03s, 260.61KB data transfered
```
`--hide-constant-logs` will stop the 2 second interval output that shows req/s and response percentiles. …

Add end of scenario report

---

mite/logoutput.py

Only append to `_resp_time_mean_store` if `_resp_time_recent` contains a value.

fix a `ZeroDivisionError` error

---

mite/__main__.py
mite/cli/test.py
mite/logoutput.py
setup.cfg

Add stddev and +/- std dev to benchmark report. 
Added new flags `--standard-deviation-response-time-threshold` and `--standard-deviation-req-sec-threshold` 
Updated mean to use statistics library and to calculate values from overall response time instead of calculating from resp_time_mean_store which has the collection of mean of response time from each instance. 
Same logic is applied for req per sec. Updated the format of report at the end. Now the report looks like this

Stddev benchmark

---

mite_kafka/__init__.py
test/test_mite_kafka.py

Update of the kafka module:
- Clean up of unused libraries
- Separation of Kafka producer and Consumer class. They still share the single context manager but now it is possible to create different object between producer and consumer
- Some methods have been update in order to use the objection mention above directly. An example is `producer = ctx.kafka_producer` and then being able to use `producer.start()` instead of `ctx.kafka.start_producer(producer)`

Update of mite_kafka module 

---

mite/logoutput.py

Reduce duration it take to generate `--report` while processing percentatge for response and request times within standard deviation by calling required `mean` and `stdev` functions once in the loop.

call mean and stdev once in a loop for report

---

mite/__main__.py
mite/cli/test.py
mite/config.py
mite/logoutput.py

Improve how `mite` handles thresholds within benchmark report and enable dynamically adding new percentiles and thresholds. Utilise `statistics` module for quatiles to calculate integer percentiles.
Change `default_config_loader` logging from info to debug.

Dynamic percentile latency report

---

mite/cli/test.py

Adding error count exceeded logging when `--max-errors-threshold` is passed in command

Adding exceed error threshold logging

---

mite_kafka/__init__.py
mite_kafka/mite_kafka_example.py

Add a kafka adapter manager mechanism to allow and manager creation of long lived producers and consumer adapter
It should be completely backwards compatible as no existing code has been changed with the exception of test code where an example has been added on how the adapter and respective decorators can be used

Add kakfa adapter manager

---

acurl/pyproject.toml
acurl/setup.cfg
acurl/setup.py
acurl/src/acurl.pyx
acurl/src/session.pyx
test-requirements.txt

Reverts sky-uk/mite#300
Unfortunately it causes a segmentation fault. Can be recreated with the following script:
```
#!/bin/bash -x
cat > s.py <<EOF
from mite_http import mite_http
scenario = lambda: [["s:journey", None, lambda s, e: 1],]
@mite_http
async def journey(ctx):
await ctx.http.get("http://localhost:8000/")
EOF
python -m http.server & HTTP_SERVER_PID=$!
mite runner & RUNNER_PID=$!
mite controller s:scenario & CONTROLLER_PID=$!
cleanup() {
kill $RUNNER_PID $CONTROLLER_PID $HTTP_SERVER_PID 2>/dev/null
rm -f s.py
}
trap cleanup EXIT INT TERM
while kill -0 $RUNNER_PID 2>/dev/null && kill -0 $CONTROLLER_PID 2>/dev/null; do sleep 1; done
cleanup
```

Revert "IDSREPERF-13 - Cython 3x migration"
